model_list:
  - model_name: gpt-4o
    litellm_params:
      model: gemini/gemini-1.5-pro-latest
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gpt-3.5-turbo-instruct
    litellm_params:
      model: gemini/gemini-1.5-pro-latest
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  drop_params: true